#!/usr/bin/env python3

import subprocess as sp
import argparse
import sys
import typing
import shlex


def get_videos(links: typing.List[str], format_options: str = "",
               title_options: str = "",
               restrict_filenames: bool = False) -> None:
    failed: typing.List[str] = []
    base_command = "youtube-dl"

    if format_options:
        base_command += ' -f "{}" '.format(format_options)

    if title_options:
        base_command += ' -o "{}" '.format(title_options)

    if restrict_filenames:
        base_command += ' --restrict_filenames '

    for link in links:
        command = base_command + '"' + link + '"'
        print('Getting "{}"...'.format(link))
        try:
            with sp.Popen(command,
                          stdout=sp.PIPE,
                          universal_newlines=True,
                          shell=True) as process:
                for line in process.stdout:
                    print(str(line[:-1]), end="\r")
        except KeyboardInterrupt:
            exit(0)
        finally:
            failed.append(link)

    if failed:
        with open("failed_links.txt", "w") as f:
            for i in failed:
                f.write(i + "\n")


def from_file(filename: str, format_options: str = "", title_options: str = "",
              restrict_filenames: bool = False) -> None:
    with open(filename, "r") as input_file:
        uris = input_file.read.split()
        get_videos(uris, format_options, title_options, restrict_filenames)


def main(argv: typing.List) -> None:
    parser = argparse.ArgumentParser(description='Download a list of videos')
    parser.add_argument('-F', metavar='FILE', type=str,
                        help='read a list of videos from a file')
    parser.add_argument('-f', metavar='FORMAT_OPTIONS', type=str,
                        help='youtube-dl video format options')
    parser.add_argument('-o', metavar='TITLE_FORMAT', type=str,
                        help='youtube-dl title format string')
    parser.add_argument('--restrict-filenames', action='store_true',
                        help='''
                        pass the "--restrict-filenames" directive to
                        youtube-dl
                        ''')
    parser.add_argument('input_uris', metavar='MEDIA_URI', type=str, nargs='*',
                        help='a list of URIs that point to a page with media')
    args = parser.parse_args(argv)

    if args.input_uris:  # If args.input_uris is *not* empty
        if args.F is not None:  # If both STDIN and a file are supplied, quit
            print("ytdl-wrapper: error: cannot read from both file and STDIN")
            exit(1)
        # Otherwise, get the media files pointed to by args.input_uris
        get_videos(args.input_uris, args.f, args.o, args.restrict_filenames)
    elif args.F is None:  # If args.input_uris is empty and args.F is None
        print("ytdl-wrapper: error: no input URIs provided")
        exit(1)
    else:  # If args.input_uris is empty and args.F is *not* None
        from_file(args.F, args.f, args.o, args.restrict_filenames)


main(sys.argv[1:])
