#!/usr/bin/env python3

import sys
import math
import numpy as np

def main(argv, argc):
	if argc < 2:
		print("USAGE: calc MATH_EXPRESSION")
		exit(1)
	
	expr = ""
	for i in argv[1:]:
		expr += " " + i

	print(eval(expr))

main(sys.argv, len(sys.argv))
